config/routes.rb
Rails.application.routes.draw do


  get 'pages/show'

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  root 'index#index'







  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'


  namespace :admin do
    root 'index#index'
    resources :pages do
      resources :trainings, shallow: true
    end
    get 'trainings', to: 'trainings#index', as: :trainings
    post 'trainings', to: 'trainings#create'
    get 'training/new', to: 'trainings#new', as: :new_training
  end

  match '/404' => 'errors#error404', via: [ :get, :post, :patch, :delete ]


  get '(*url)', to: 'pages#show', as: :page_show, url: /.*/
end

app/views/admin/pages/_form.html.haml
= simple_form_for([:admin, @page]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :url
    = f.input :title
    = f.input :body, as: :ckeditor

  .form-actions
    = f.button :submit

app/views/admin/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', admin_page_path(@page)
\|
= link_to 'Back', admin_pages_path

app/views/admin/pages/index.html.haml
%h1 Listing pages

%table.table-bordered.table-hover.table-striped
  %thead
    %tr
      %th Url
      %th Title
      %th Description
      %th Keywords
      -#%th Body
      %th
      %th
      %th

  %tbody
    - @pages.each do |page|
      %tr
        %td= page.url
        %td= page.title
        %td= link_to 'Show', admin_page_path(page)
        %td= link_to 'Edit', edit_admin_page_path(page)
        %td= link_to 'Destroy', admin_page_path(page), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Page', new_admin_page_path

app/views/admin/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', admin_pages_path

app/views/admin/pages/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @page.url
%p
  %b Title:
  = @page.title
%p
  %b Body:
  = @page.body.html_safe

= link_to 'Edit', edit_admin_page_path(@page)
\|
= link_to 'Back', admin_pages_path