config/routes.rb
Rails.application.routes.draw do


  get 'pages/show'

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  root 'index#index'







  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'


  namespace :admin do
    root 'index#index'
    resources :pages do
      resources :trainings, shallow: true
    end
    get 'trainings', to: 'trainings#index', as: :trainings
    post 'trainings', to: 'trainings#create'
    get 'training/new', to: 'trainings#new', as: :new_training
  end

  match '/404' => 'errors#error404', via: [ :get, :post, :patch, :delete ]


  get '(*url)', to: 'pages#show', as: :page_show, url: /.*/
end

app/views/index/index.html.haml
- content_for :title, t(:index_title)
- content_for :description, t(:index_description)
- content_for :keywords, t(:index_keywords)
#main
  = @index_page.body.html_safe

  .row
    .col-md-6
      .box.box-solid
        .box-body
          %a.image.featured{:href => '/yoga_with_partner'}
            = image_tag 'yoga2.jpg'
          %a{:href => '/yoga_with_partner'}
            %h4
              Йога с партнером
        .box-footer
          .social
            .vk
              :javascript
                document.write(VK.Share.button({url: "#{page_show_url('yoga_with_partner')}"},{type: "link", text: "Сохранить"}));
            .fb
              .fb-like{ data: { href: page_show_url('yoga_with_partner'), layout: 'button_count', action: 'like', 'show-faces'=>'false', share:'true'} }
    .col-md-6
      .box.box-solid
        .box-body
          %a.image.featured{:href => '/family'}
            = image_tag 'yoga5.jpg'
          %a{:href => '/family'}
            %h4
              Семья - искусство любить
        .box-footer
          .social
            .vk
              :javascript
                document.write(VK.Share.button({url: "#{page_show_url('family')}"},{type: "link", text: "Сохранить"}));
            .fb
              .fb-like{ data: { href: page_show_url('family'), layout: 'button_count', action: 'like', 'show-faces'=>'false', share:'true'} }
  .row
    .col-md-6
      .box.box-solid
        .box-body
          %a.image.featured{:href => '/sexuality_and_spirituality'}
            = image_tag 'yoga1.jpg'
          %a{:href => '/sexuality_and_spirituality'}
            %h4
              Сексуальность и духовность
        .box-footer
          .social
            .vk
              :javascript
                document.write(VK.Share.button({url: "#{page_show_url('sexuality_and_spirituality')}"},{type: "link", text: "Сохранить"}));
            .fb
              .fb-like{ data: { href: page_show_url('sexuality_and_spirituality'), layout: 'button_count', action: 'like', 'show-faces'=>'false', share:'true'} }
    .col-md-6
      .box.box-solid
        .box-body
          %a.image.featured{:href => '/art_of_being_woman'}
            = image_tag '244579551.jpg'
          %a{:href => '/art_of_being_woman'}
            %h4
              Искусство быть женщиной
        .box-footer
          .social
            .vk
              :javascript
                document.write(VK.Share.button({url: "#{page_show_url('art_of_being_woman')}"},{type: "link", text: "Сохранить"}));
            .fb
              .fb-like{ data: { href: page_show_url('art_of_being_woman'), layout: 'button_count', action: 'like', 'show-faces'=>'false', share:'true'} }