config/routes.rb
Rails.application.routes.draw do


  get 'pages/show'

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  root 'index#index'







  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'


  namespace :admin do
    root 'index#index'
    resources :pages do
      resources :trainings, shallow: true
    end
    get 'trainings', to: 'trainings#index', as: :trainings
    post 'trainings', to: 'trainings#create'
    get 'training/new', to: 'trainings#new', as: :new_training
  end

  match '/404' => 'errors#error404', via: [ :get, :post, :patch, :delete ]


  get '(*url)', to: 'pages#show', as: :page_show, url: /.*/
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :page, dependent: :destroy

  after_create :update_temporary_page

  validates_presence_of :date_start, :date_end, :place, :title, :body, :avatar
  validates :active, inclusion: { in: [ true, false ] }

  mount_uploader :avatar, AvatarUploader

  # Update params for page
  def update_temporary_page
    self.page.update(url: "trainings/#{ self.id }", title: "#{ self.title }", body: "#{ self.body }")
  end
end

app/controllers/admin/trainings_controller.rb
class Admin::TrainingsController < Admin::AdminController
  before_action :set_training, only: [:show, :edit, :update, :destroy]
  before_action :clear_temporary_page, :set_temporary_page, only: :create
  after_action :clear_temporary_page, only: :create

  # GET /trainings
  def index
    @trainings = Training.all
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params.merge(page_id: @page.id))
    respond_to do |format|
      if @training.save
        format.html { redirect_to admin_training_path(@training), notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to admin_training_path(@training), notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
        @training.update_temporary_page
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to admin_trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Create temporary object Page for create Training with page_id
    def set_temporary_page
      @page = Page.create(url: "temporary", title: "temporary", body: "temporary")
    end

    def clear_temporary_page
      page = Page.find_by(url: "temporary", title: "temporary", body: "temporary")
      page.delete if page
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:date_start, :date_end, :place, :active, :title, :body, :avatar)
    end
end

app/views/admin/trainings/_form.html.haml
= simple_form_for([:admin, @page, @training], html: { multipart: true }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :place
    = f.input :active do
      = f.collection_radio_buttons :active, [[true, 'Yes'] ,[false, 'No']], :first, :last
    = f.input :date_start do
      = f.date_select :date_start, :order => [:day, :month, :year]
    = f.input :date_end do
      = f.date_select :date_end, :order => [:day, :month, :year]
    = f.input :avatar do
      = f.file_field :avatar
    = f.input :body, as: :ckeditor

  .form-actions
    = f.button :submit

app/views/admin/trainings/edit.html.haml
%h1 Editing training

= render 'form'

= link_to 'Show', admin_training_path(@training)
\|
= link_to 'Back', admin_trainings_path

app/views/admin/trainings/index.html.haml
%h1 Listing training

%table.table-bordered.table-hover.table-striped
  %thead
    %tr
      %th Url
      %th Place
      %th Title
      %th Start
      %th End
      %th Active
      %th
      %th
      %th

  %tbody
    - @trainings.each do |training|
      %tr
        %td= training.page.url
        %td= training.place
        %td= training.title
        %td= training.date_start
        %td= training.date_end
        %td= training.active
        %td= link_to 'Show', admin_training_path(training)
        %td= link_to 'Edit', edit_admin_training_path(training)
        %td= link_to 'Destroy', admin_training_path(training), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Training', admin_new_training_path

app/views/admin/trainings/new.html.haml
%h1 New training

= render 'form'

= link_to 'Back', admin_trainings_path

app/views/admin/trainings/show.html.haml
%p#notice= notice

%p
  %b Avatar:
  = image_tag("#{@training.avatar.thumb.url}")
%p
  %b Url:
  = @training.page.url
%p
  %b Date:
  = "#{@training.date_start} - #{@training.date_end}"
%p
  %b Place:
  = @training.place
%p
  %b Active:
  = @training.active
%p
  %b Title:
  = @training.title
%p
  %b Body:
  = @training.body.html_safe

= link_to 'Edit', edit_admin_training_path(@training)
\|
= link_to 'Back', admin_trainings_path